auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

ingester:
  wal:
    enabled: true
    dir: /wal
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /wal/index
  filesystem:
    directory: /wal/chunks

limits_config:
  enforce_metric_name: false





